# Site settings
title: God's Mission Orphanage
SEOTitle: Orphelinat La Mission De Dieu -Kinshasa (God's Mission Orphanage)
author: God's Mission Orphanage
header-img: img/home-bg.jpg
default-img: "/img/default-image.jpg"
email: tatizblog@gmail.com
description: "God's mission Orphanage is located in the Democratic Republic of the Congo with 40 children."
keyword: "orphanage, kinshasa, Congo DRC, Orphelinat, Democraatic Republic of the Congo"
url: "https://godsmissionorphanage.org" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Sidebar settings
sidebar: true # whether or not using Sidebar.

# Publish posts or collection documents with a future date.
future: true

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate_path: "news/page:num/"
paginate: 5
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: God-s-Mission-Orphanage

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Verses calling you
verses:
  [
    { title: "James 1:27", href: "https://www.bible.com/bible/111/JAS.1.27.NIV" },
    { title: "Matthew 25:35-40", href: "https://www.bible.com/bible/111/MAT.25.35-40.NIV" },
    { title: "Psalm 82:3", href: "https://www.bible.com/bible/111/PSA.82.3.NIV" },
  ]

needs:
  [
    { name: "Eating three meals a day?",  met: "❌",    unmet: "It's been 3 weeks that children haven't had even 2 meals/day"},
    { name: "Children in school this month",    met: "34" ,   unmet: "6"},
    { name: "Rent",                       met: "$0",  unmet: "$700"},

    { name: "Number of sick children in the hospital", met: "0", unmet: "0"},

    { name: "Building a shelter",         met: "$320",      unmet: "$59,680"},
    { name: "School fees", met: "" ,      unmet: "$300"}
  ]